### ISSUE TITLE
Some error when training

### ISSUE THREAD

**Issue by zhangyin1996** [jichengyuan/Cooperitive_Students#3]
Hi, I have some problem when I trained the code
1. When the number of iterations reaches 76000, an error will be reported:

RuntimeError: [/opt/conda/conda-bld/pytorch_1639180544224/work/third_party/gloo/gloo/transport/tcp/pair.cc:598] Connection closed by peer [127.0.1.1]:13204
Traceback (most recent call last):
  File "train_net.py", line 82, in <module>
    launch(
  File "/home/disk/zhangy/paper_recurrence/2pcnet/detectron2/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/home/disk/zhangy/anaconda3/envs/dt2=0.6_torch=1.10.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/disk/zhangy/anaconda3/envs/dt2=0.6_torch=1.10.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/disk/zhangy/anaconda3/envs/dt2=0.6_torch=1.10.1/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/disk/zhangy/paper_recurrence/2pcnet/detectron2/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/home/disk/zhangy/work3/ispteacher_cos/train_net.py", line 76, in main
    return trainer.train()
  File "/home/disk/zhangy/work3/ispteacher_cos/coStudents/engine/trainer_cos.py", line 392, in train
    self.train_loop(self.start_iter, self.max_iter)
  File "/home/disk/zhangy/work3/ispteacher_cos/coStudents/engine/trainer_cos.py", line 410, in train_loop
    self.run_step_full_semisup()
  File "/home/disk/zhangy/work3/ispteacher_cos/coStudents/engine/trainer_cos.py", line 607, in run_step_full_semisup
    self.cfg.SEMISUPNET.BBOX_THRESHOLD = self.update_threshold(cur_threshold, filter_cls_confidence,
  File "/home/disk/zhangy/work3/ispteacher_cos/coStudents/engine/trainer_cos.py", line 526, in update_threshold
    mu = sum(top_50_percent_scores) / len(top_50_percent_scores)
ZeroDivisionError: division by zero

2. And when I resume it, this problem could be solved. But when the number of iterations reaches 90000, there is another error, the loss is nan.

[04/12 18:49:50] d2.utils.events INFO:  eta: 9:55:52  iter: 90019  total_loss: nan  loss_cls: nan  loss_box_reg: nan  loss_rpn_cls: 0.1468  loss_rpn_loc: 0.08936  loss_rpn_cls_pseudo: 0.01148  loss_rpn_loc_pseudo: 0.0255    time: 3.5911  last_time: 3.0864  data_time: 0.0367  last_data_time: 0.0273   lr: 0.0225  max_mem: 19389M
[04/12 18:50:51] d2.utils.events INFO:  eta: 9:53:49  iter: 90039  total_loss: nan  loss_cls: nan  loss_box_reg: nan  loss_rpn_cls: 0.5992  loss_rpn_loc: 0.1223  loss_rpn_cls_pseudo: 0.559  loss_rpn_loc_pseudo: 0    time: 3.5906  last_time: 2.9945  data_time: 0.0398  last_data_time: 0.0648   lr: 0.0225  max_mem: 19389M
[04/12 18:51:53] d2.utils.events INFO:  eta: 9:51:41  iter: 90059  total_loss: nan  loss_cls: nan  loss_box_reg: nan  loss_rpn_cls: 0.5527  loss_rpn_loc: 0.1245  loss_rpn_cls_pseudo: 0.4813  loss_rpn_loc_pseudo: 0    time: 3.5901  last_time: 3.3306  data_time: 0.0276  last_data_time: 0.0198   lr: 0.0225  max_mem: 19389M
[04/12 18:52:54] d2.utils.events INFO:  eta: 9:50:01  iter: 90079  total_loss: nan  loss_cls: nan  loss_box_reg: nan  loss_rpn_cls: 0.5063  loss_rpn_loc: 0.1253  loss_rpn_cls_pseudo: 0.4157  loss_rpn_loc_pseudo: 0    time: 3.5895  last_time: 2.9285  data_time: 0.0434  last_data_time: 0.0211   lr: 0.0225  max_mem: 19389M
[04/12 18:53:55] d2.utils.events INFO:  eta: 9:48:17  iter: 90099  total_loss: nan  loss_cls: nan  loss_box_reg: nan  loss_rpn_cls: 0.4824  loss_rpn_loc: 0.1156  loss_rpn_cls_pseudo: 0.3644  loss_rpn_loc_pseudo: 0    time: 3.5890  last_time: 2.9097  data_time: 0.0381  last_data_time: 0.0216   lr: 0.0225  max_mem: 19389M
[04/12 18:54:56] d2.utils.events INFO:  eta: 9:46:24  iter: 90119  total_loss: nan  loss_cls: nan  loss_box_reg: nan  loss_rpn_cls: 0.459  loss_rpn_loc: 0.1234  loss_rpn_cls_pseudo: 0.3245  loss_rpn_loc_pseudo: 0    time: 3.5885  last_time: 3.0362  data_time: 0.0333  last_data_time: 0.0182   lr: 0.0225  max_mem: 19389M
[04/12 18:55:57] d2.utils.events INFO:  eta: 9:44:10  iter: 90139  total_loss: nan  loss_cls: nan  loss_box_reg: nan  loss_rpn_cls: 0.4437  loss_rpn_loc: 0.1249  loss_rpn_cls_pseudo: 0.2934  loss_rpn_loc_pseudo: 0    time: 3.5879  last_time: 3.2479  data_time: 0.0399  last_data_time: 0.0692   lr: 0.0225  max_mem: 19389M

the environment is the same as 2pcnet. Could you please help me find out where the problem lies?

**Comment by jichengyuan** [comment]
Hi @zhangyin1996 , thank you for getting interested in our work. I did not face this issue during my training. Could you please use the below command to print the env info and put them here?

`wget -nc -q https://github.com/facebookresearch/detectron2/raw/master/detectron2/utils/collect_env.py && python collect_env.py`

best,

**Comment by zhangyin1996** [comment]
@jichengyuan 
Thank you for your reply. the information is:

-------------------------------  -----------------------------------------------------------------------------------------------------
sys.platform                     linux
Python                           3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) [GCC 10.3.0]
numpy                            1.22.3
detectron2                       0.6 @/home/disk/zhangy/paper_recurrence/2pcnet/detectron2/detectron2
Compiler                         GCC 7.5
CUDA compiler                    CUDA 10.2
detectron2 arch flags            7.5
DETECTRON2_ENV_MODULE            <not set>
PyTorch                          1.10.1 @/home/disk/zhangy/anaconda3/envs/dt2=0.6_torch=1.10.1/lib/python3.8/site-packages/torch
PyTorch debug build              False
torch._C._GLIBCXX_USE_CXX11_ABI  False
GPU available                    Yes
GPU 0,1,2,3                      Quadro RTX 6000 (arch=7.5)
Driver version                   440.33.01
CUDA_HOME                        /home/disk/zhangy/cuda-10.2
Pillow                           9.0.1
torchvision                      0.11.2 @/home/disk/zhangy/anaconda3/envs/dt2=0.6_torch=1.10.1/lib/python3.8/site-packages/torchvision
torchvision arch flags           3.5, 5.0, 6.0, 7.0, 7.5
fvcore                           0.1.5.post20221221
iopath                           0.1.9
cv2                              4.7.0
-------------------------------  -----------------------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON

**Comment by jichengyuan** [comment]
Hi @zhangyin1996,

sorry for the late response.

I checked my env, I used torch==1.10., torchaudio==0.10., and torchvision==0.11.2. Could you have a try with pytorch 1.10?

best,

**Comment by zhangyin1996** [comment]
@jichengyuan 
My environment is also torch==1.10.1, torchvision==0.11.2.
 I think ther are some another problems,  thank you for your reply!

**Comment by zhangyin1996** [comment]
@jichengyuan 
I solved the problem by adding a line of 'if' branch code, so I would also close this issue.
Thank you!
